pipeline {
    agent any

    tools {
        maven 'Maven3' // Ensure Maven is installed and configured in Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out source code...'
                git branch: 'main', url: 'https://github.com/vernere/mavenTest.git'
            }
        }
        stage('Build') {
            steps {
                echo 'Building...'
                dir('demo') {
                    bat 'mvn clean install'
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
                dir('demo') {
                    bat 'mvn clean install'
                }
            }
        }
        stage('Code coverage') {
            steps {
                echo 'Calculating code coverage...'
                dir('demo') {
                    bat 'mvn jacoco:report'
                }
            }
        }
        stage('Publish test Reports') {
            steps {
                echo 'Publishing reports...'
                junit '**/target/surefire-reports/*.xml'
            }
        }
        stage('publish coverage reports') {
            steps {
                echo 'Publishing coverage reports...'
                jacoco()
            }
        }
    }
}